kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wisecow-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
      - containerPort: 443
        hostPort: 30443
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /etc/hosts
        containerPath: /etc/hosts
    # Add CPU/memory resources (optional but helpful)
    image: kindest/node:v1.29.2

