jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug secrets
        run: |
          echo "Username: '${{ secrets.DOCKERHUB_USERNAME }}'"
          TOKEN="${{ secrets.DOCKERHUB_TOKEN }}"
          echo "Token is empty? -> $([ -z "$TOKEN" ] && echo yes || echo no)"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # continue with your Docker build, push, etc.

